version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  backend:
    image: ${DOCKERHUB_USERNAME}/my-tg-app-backend:latest
    restart: always
    env_file: .env.prod
    depends_on:
      - mongo
    networks:
      - app-network

  nginx:
    image: ${DOCKERHUB_USERNAME}/my-tg-app-nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - app-network
    # Просто запускаем nginx, он будет слушать 80 порт согласно nginx.conf
    command: nginx -g 'daemon off;'

  certbot:
    image: certbot/certbot
    # Эта команда запустится, получит сертификат для домена и завершится
    command: certonly --webroot --webroot-path=/var/www/certbot --email hitomi.jpeg@gmail.com -d ariyapoizon.ru --agree-tos --no-eff-email --force-renewal
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge