# ./docker-compose.yml
version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Контекст сборки - папка backend
      dockerfile: Dockerfile
    restart: always
    env_file: .env # Для локалки используй простой .env
    depends_on:
      - mongo
    networks:
      - app-network
    # Для локальной разработки можно прокинуть volume, чтобы не пересобирать контейнер на каждое изменение
    volumes:
      - ./backend:/app
      - /app/node_modules # Исключаем node_modules из volume, чтобы использовались те, что внутри контейнера

  nginx:
    build:
      context: . # Контекст сборки - корень проекта
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - app-network

  # Certbot оставляем без изменений, он не зависит от кода

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge