version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongo:27017/orders
    env_file:
      - .env.prod

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./front/dist:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  mongo_data: